name: smart_cooler_app

description: Android WebView UI for ESP32 Smart Cooler REST JSON API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  # نسخه‌های قدیمی file_picker با Flutter/Android جدید روی GitHub Actions
  # با compileSdk 34 ساخته می‌شوند و خطای API 36 می‌دهند.
  file_picker: ^10.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/web/index.html
