name: smart_cooler_app

description: Android Flutter UI for ESP32 Smart Cooler REST JSON API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

flutter:
  uses-material-design: true
